web:
    build: web
    links:
     - db
     - redis
     - beanstalkd
    ports:
     - "80:80"
db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
    volumes:
     - /var/lib/mysql
redis:
    image: redis
beanstalkd:
    build: beanstalkd
